### ISSUE TITLE
关于网络结构的搭建问题

### ISSUE THREAD

**Issue by librahfacebook** [DengPingFan/DAVSOD#10]
您好，很感谢您能提供工程代码部分。现在我用PyTorch将整个网络结构进行重建，中间有几个问题想询问一下：（1）Resnet50中后面部分stride改为1的原因是什么？（2）reshape的参数设置（3，1，32，60，60），其中3指的是时间序列数？1指的批次？（3）后面ConvLSTM结构和原作者论文中说的结构一样吗？去年我将PDC结构训练了几次，发现网络模型的训练效果并不理想，损失函数到一定程度始终下降不来，请问你们训练时先利用静态图像数据集对PDC网络进行训练，然后再利用DAVSOD对整体网络进行训练吗？非常感谢！！！

**Comment by DengPingFan** [comment]
你好，感谢你对这个项目感兴趣。这边已经有一些学者用pytorch复现类似的网络，得到了更好的结果，到时候可以分享给你。回答你的问题：1，改为1是想让采样损失少一些 2.  3. ConvLSTM和ECCV的PDB结构一样。注意大部分视频中的情况没有一直发生attention shift，因此静态网络的训练很重要，我们是先把头部训练到最高了以后，再来联合训练，学习一下shift的attention. 如果还有进一步的问题，可以加我的QQ：381620505.

**Comment by DengPingFan** [comment]
（2）reshape的参数设置（3，1，32，60，60），其中3指的是时间序列数？1指的批次？
3是时间序列数，1是每次处理一个bs

**Comment by librahfacebook** [comment]
非常感谢您的回复，我这边QQ由于身份验证加不了，可以加一下我的QQ号吗？我的QQ号为1584587945.
