### ISSUE TITLE
Question about caffe build

### ISSUE THREAD

**Issue by karliell** [DengPingFan/DAVSOD#11]
Thank you so much for your amazing work! I have some questions about Caffe build.
I use windows. May I ask should I do this step from link on the Caffe website that you provide?
![image](https://user-images.githubusercontent.com/36145675/79145434-a5e07480-7d8e-11ea-8706-36a657c84568.png)
[caffe windows](https://github.com/BVLC/caffe/tree/windows)

I met problems when I build this. It's not successful when I am on the last step. `build_win.cmd`. Should I use the `makefile.config` that you provide? Which folder should I put? Thank you so much for your help!!!

**Comment by DengPingFan** [comment]
Hi, 
    This code has not been tested on the windows. You need to have a try for several times to fix some bugs.
