### ISSUE TITLE
求pytorch版本

### ISSUE THREAD

**Issue by lhl190628563746** [DengPingFan/DAVSOD#15]
大佬，什么时候能发一下ssav的pytorch版本

**Comment by JingZhang617** [comment]
你好，我们正在开发pytorch版本，很快会上传，请关注页面：https://github.com/JingZhang617/SSAV-Pytorch/。谢谢

**Comment by ruoqi77** [comment]
Hi, do you still plan on releasing pytorch code and when?

**Comment by DengPingFan** [comment]
Hi, we are setting up another more important task (Concealed Object Detection, arXiv, 2021). Thus, delay this task. However, we will continue to the extent of the journal version in the near future (Maybe need one more year).  As we know, there are many recent works that have achieved better performance than SSAV even utilize the weakly supervised manner.  Please refer to the recent CVPR 2021 model: Weakly Supervised Video Salient Object Detection.

Best,

**Comment by ruoqi77** [comment]
Thanks for your excellent work and patient reply !
