### ISSUE TITLE
你好请问下关于输入太大的问题。

### ISSUE THREAD

**Issue by myEnglishIsPool** [DengPingFan/DAVSOD#17]
您好看了您的论文，使用的是lstm那输入也是一个视频里的连续图片哈，但我遇到问题就是train里面最长的帧都有400多张图片了，一次性输入进去（特别是HW都是400多有点大），显存12G不够用。请问您当时遇到过这个问题吗？是否可以把400帧的视频剪成2个200帧来做？谢谢。

**Comment by DengPingFan** [comment]
> 您好看了您的论文，使用的是lstm那输入也是一个视频里的连续图片哈，但我遇到问题就是train里面最长的帧都有400多张图片了，一次性输入进去（特别是HW都是400多有点大），显存12G不够用。请问您当时遇到过这个问题吗？是否可以把400帧的视频剪成2个200帧来做？谢谢。

可以的，否则就只能用大内存的显卡了。
