### ISSUE TITLE
make: *** [.build_release/cuda/src/caffe/layers/conv_lstm_unit_layer.o] Error 1

### ISSUE THREAD

**Issue by weilanShi** [DengPingFan/DAVSOD#2]
when i  build mycaffe-convlstm, The problem arises：

./include/caffe/layers/conv_lstm_layer.hpp(48): warning: field initializers are a C++11 feature

./include/caffe/layers/conv_lstm_layer.hpp(48): warning: field initializers are a C++11 feature

./include/caffe/layers/conv_lstm_layer.hpp(48): warning: field initializers are a C++11 feature

./include/caffe/layers/conv_lstm_layer.hpp(48): warning: field initializers are a C++11 feature

./include/caffe/layers/conv_lstm_layer.hpp(48): warning: field initializers are a C++11 feature

./include/caffe/layers/conv_lstm_layer.hpp(48): warning: field initializers are a C++11 feature

./include/caffe/layers/conv_lstm_layer.hpp(48): warning: field initializers are a C++11 feature

./include/caffe/layers/conv_lstm_helper.hpp(88): error: explicit type is missing ("int" assumed)

./include/caffe/layers/conv_lstm_helper.hpp(88): error: expected a ";"

./include/caffe/layers/conv_lstm_helper.hpp(88): error: expected an expression

./include/caffe/layers/conv_lstm_helper.hpp(88): error: expected a ";"

./include/caffe/layers/conv_lstm_helper.hpp(89): error: no instance of overloaded function "caffe::LayerParameter::add_bottom" matches the argument list
            argument types are: (int)
            object type is: caffe::LayerParameter

./include/caffe/layers/conv_lstm_helper.hpp(137): error: explicit type is missing ("int" assumed)

./include/caffe/layers/conv_lstm_helper.hpp(137): error: expected a ";"

./include/caffe/layers/conv_lstm_helper.hpp(137): error: expected an expression

./include/caffe/layers/conv_lstm_helper.hpp(137): error: expected a ";"

./include/caffe/layers/conv_lstm_helper.hpp(138): error: no instance of overloaded function "caffe::LayerParameter::add_bottom" matches the argument list
            argument types are: (int)
            object type is: caffe::LayerParameter

./include/caffe/layers/conv_lstm_layer.hpp(48): warning: field initializers are a C++11 feature

10 errors detected in the compilation of "/tmp/tmpxft_00003098_00000000-5_conv_lstm_unit_layer.cpp4.ii".
Makefile:606: recipe for target '.build_release/cuda/src/caffe/layers/conv_lstm_unit_layer.o' failed
make: *** [.build_release/cuda/src/caffe/layers/conv_lstm_unit_layer.o] Error 1
make: *** Waiting for unfinished jobs....

But there is no problem in compiling the original caffe. What's the reason for this?

**Comment by DengPingFan** [comment]
Hi, Maybe you need to reconfig your c++ setting in your config file.

Also, please check your environments: ubuntu 16.04+ openCV 3.1 + Cuda 8.0

**Comment by DengPingFan** [comment]
Before you make pycaffe, please make clean it. 
If you still cannot address this issue, please don't hesitate to contact me.

**Comment by weilanShi** [comment]
> Before you make pycaffe, please make clean it.
> If you still cannot address this issue, please don't hesitate to contact me.
Thank you very much for your reply. I have another question，does the mycaffe-convlstm also need to compile matlab?

**Comment by DengPingFan** [comment]
No, there is no need to compile matlab.

**Comment by weilanShi** [comment]
> No, there is no need to compile matlab.

Thank you very much for your timely reply. With your help, I have configured mycaffe-convlstm, but a new problem arises during the test:

I0627 10:43:47.981047  5263 net.cpp:129] Top shape: 3 3 473 473 (2013561)
I0627 10:43:47.981057  5263 net.cpp:129] Top shape: 3 (3)
I0627 10:43:47.981065  5263 net.cpp:137] Memory required for data: 8054256
I0627 10:43:47.981075  5263 layer_factory.hpp:77] Creating layer clip_markers
I0627 10:43:47.981088  5263 net.cpp:84] Creating Layer clip_markers
I0627 10:43:47.981098  5263 net.cpp:380] clip_markers -> reshape-cm
I0627 10:43:47.981115  5263 hdf5_data_layer.cpp:80] Loading list of HDF5 filenames from: ./txt/seq_t5_n1.txt
F0627 10:43:47.981138  5263 hdf5_data_layer.cpp:89] Failed to open source file: ./txt/seq_t5_n1.txt
*** Check failure stack trace: ***
Aborted (core dumped)

But I don't know why. I'm here to ask you.

**Comment by DengPingFan** [comment]
I0627 10:43:47.981065 5263 net.cpp:137] Memory required for data: 8054256， 

I guess this is the out of memory.   You need a 12G GPU. Please check your GPU memory meet this requires.

**Comment by weilanShi** [comment]
> I0627 10:43:47.981065 5263 net.cpp:137] Memory required for data: 8054256，
> 
> I guess this is the out of memory. You need a 12G GPU. Please check your GPU memory meet this requires.
thank you for your reply. Maybe it's not the GPU memory problem. Error Reporting Display： Failed to open source file: ./txt/seq_t5_n1.txt， and this  file: seq_t5_n1.txt does not exist in the txt folder, how can we get the file?

**Comment by DengPingFan** [comment]
Please redownload the file in the ./txt/seq_t5_n1.txt. Thanks.

**Comment by weilanShi** [comment]
> Please redownload the file in the ./txt/seq_t5_n1.txt. Thanks.



The problem has been solved. Thank you very much for asking you such a silly question.

**Comment by GewelsJI** [comment]
> when i build mycaffe-convlstm, The problem arises：
> 
> ./include/caffe/layers/conv_lstm_layer.hpp(48): warning: field initializers are a C++11 feature
> 
> ./include/caffe/layers/conv_lstm_layer.hpp(48): warning: field initializers are a C++11 feature
> 
> ./include/caffe/layers/conv_lstm_layer.hpp(48): warning: field initializers are a C++11 feature
> 
> ./include/caffe/layers/conv_lstm_layer.hpp(48): warning: field initializers are a C++11 feature
> 
> ./include/caffe/layers/conv_lstm_layer.hpp(48): warning: field initializers are a C++11 feature
> 
> ./include/caffe/layers/conv_lstm_layer.hpp(48): warning: field initializers are a C++11 feature
> 
> ./include/caffe/layers/conv_lstm_layer.hpp(48): warning: field initializers are a C++11 feature
> 
> ./include/caffe/layers/conv_lstm_helper.hpp(88): error: explicit type is missing ("int" assumed)
> 
> ./include/caffe/layers/conv_lstm_helper.hpp(88): error: expected a ";"
> 
> ./include/caffe/layers/conv_lstm_helper.hpp(88): error: expected an expression
> 
> ./include/caffe/layers/conv_lstm_helper.hpp(88): error: expected a ";"
> 
> ./include/caffe/layers/conv_lstm_helper.hpp(89): error: no instance of overloaded function "caffe::LayerParameter::add_bottom" matches the argument list
> argument types are: (int)
> object type is: caffe::LayerParameter
> 
> ./include/caffe/layers/conv_lstm_helper.hpp(137): error: explicit type is missing ("int" assumed)
> 
> ./include/caffe/layers/conv_lstm_helper.hpp(137): error: expected a ";"
> 
> ./include/caffe/layers/conv_lstm_helper.hpp(137): error: expected an expression
> 
> ./include/caffe/layers/conv_lstm_helper.hpp(137): error: expected a ";"
> 
> ./include/caffe/layers/conv_lstm_helper.hpp(138): error: no instance of overloaded function "caffe::LayerParameter::add_bottom" matches the argument list
> argument types are: (int)
> object type is: caffe::LayerParameter
> 
> ./include/caffe/layers/conv_lstm_layer.hpp(48): warning: field initializers are a C++11 feature
> 
> 10 errors detected in the compilation of "/tmp/tmpxft_00003098_00000000-5_conv_lstm_unit_layer.cpp4.ii".
> Makefile:606: recipe for target '.build_release/cuda/src/caffe/layers/conv_lstm_unit_layer.o' failed
> make: *** [.build_release/cuda/src/caffe/layers/conv_lstm_unit_layer.o] Error 1
> make: *** Waiting for unfinished jobs....
> 
> But there is no problem in compiling the original caffe. What's the reason for this?

How to solve this problem? I have meet the same problem but have no idea to address it

**Comment by weilanShi** [comment]
> > when i build mycaffe-convlstm, The problem arises：
> > ./include/caffe/layers/conv_lstm_layer.hpp(48): warning: field initializers are a C++11 feature
> > ./include/caffe/layers/conv_lstm_layer.hpp(48): warning: field initializers are a C++11 feature
> > ./include/caffe/layers/conv_lstm_layer.hpp(48): warning: field initializers are a C++11 feature
> > ./include/caffe/layers/conv_lstm_layer.hpp(48): warning: field initializers are a C++11 feature
> > ./include/caffe/layers/conv_lstm_layer.hpp(48): warning: field initializers are a C++11 feature
> > ./include/caffe/layers/conv_lstm_layer.hpp(48): warning: field initializers are a C++11 feature
> > ./include/caffe/layers/conv_lstm_layer.hpp(48): warning: field initializers are a C++11 feature
> > ./include/caffe/layers/conv_lstm_helper.hpp(88): error: explicit type is missing ("int" assumed)
> > ./include/caffe/layers/conv_lstm_helper.hpp(88): error: expected a ";"
> > ./include/caffe/layers/conv_lstm_helper.hpp(88): error: expected an expression
> > ./include/caffe/layers/conv_lstm_helper.hpp(88): error: expected a ";"
> > ./include/caffe/layers/conv_lstm_helper.hpp(89): error: no instance of overloaded function "caffe::LayerParameter::add_bottom" matches the argument list
> > argument types are: (int)
> > object type is: caffe::LayerParameter
> > ./include/caffe/layers/conv_lstm_helper.hpp(137): error: explicit type is missing ("int" assumed)
> > ./include/caffe/layers/conv_lstm_helper.hpp(137): error: expected a ";"
> > ./include/caffe/layers/conv_lstm_helper.hpp(137): error: expected an expression
> > ./include/caffe/layers/conv_lstm_helper.hpp(137): error: expected a ";"
> > ./include/caffe/layers/conv_lstm_helper.hpp(138): error: no instance of overloaded function "caffe::LayerParameter::add_bottom" matches the argument list
> > argument types are: (int)
> > object type is: caffe::LayerParameter
> > ./include/caffe/layers/conv_lstm_layer.hpp(48): warning: field initializers are a C++11 feature
> > 10 errors detected in the compilation of "/tmp/tmpxft_00003098_00000000-5_conv_lstm_unit_layer.cpp4.ii".
> > Makefile:606: recipe for target '.build_release/cuda/src/caffe/layers/conv_lstm_unit_layer.o' failed
> > make: *** [.build_release/cuda/src/caffe/layers/conv_lstm_unit_layer.o] Error 1
> > make: *** Waiting for unfinished jobs....
> > But there is no problem in compiling the original caffe. What's the reason for this?
> 
> How to solve this problem? I have meet the same problem but have no idea to address it

You can refer to this： https://github.com/agethen/ConvLSTM-for-Caffe  （Notes on Compiling）

**Comment by MengqiDLuffy** [comment]
> when i build mycaffe-convlstm, The problem arises：
> 
> ./include/caffe/layers/conv_lstm_layer.hpp(48): warning: field initializers are a C++11 feature
> 
> ./include/caffe/layers/conv_lstm_layer.hpp(48): warning: field initializers are a C++11 feature
> 
> ./include/caffe/layers/conv_lstm_layer.hpp(48): warning: field initializers are a C++11 feature
> 
> ./include/caffe/layers/conv_lstm_layer.hpp(48): warning: field initializers are a C++11 feature
> 
> ./include/caffe/layers/conv_lstm_layer.hpp(48): warning: field initializers are a C++11 feature
> 
> ./include/caffe/layers/conv_lstm_layer.hpp(48): warning: field initializers are a C++11 feature
> 
> ./include/caffe/layers/conv_lstm_layer.hpp(48): warning: field initializers are a C++11 feature
> 
> ./include/caffe/layers/conv_lstm_helper.hpp(88): error: explicit type is missing ("int" assumed)
> 
> ./include/caffe/layers/conv_lstm_helper.hpp(88): error: expected a ";"
> 
> ./include/caffe/layers/conv_lstm_helper.hpp(88): error: expected an expression
> 
> ./include/caffe/layers/conv_lstm_helper.hpp(88): error: expected a ";"
> 
> ./include/caffe/layers/conv_lstm_helper.hpp(89): error: no instance of overloaded function "caffe::LayerParameter::add_bottom" matches the argument list
> argument types are: (int)
> object type is: caffe::LayerParameter
> 
> ./include/caffe/layers/conv_lstm_helper.hpp(137): error: explicit type is missing ("int" assumed)
> 
> ./include/caffe/layers/conv_lstm_helper.hpp(137): error: expected a ";"
> 
> ./include/caffe/layers/conv_lstm_helper.hpp(137): error: expected an expression
> 
> ./include/caffe/layers/conv_lstm_helper.hpp(137): error: expected a ";"
> 
> ./include/caffe/layers/conv_lstm_helper.hpp(138): error: no instance of overloaded function "caffe::LayerParameter::add_bottom" matches the argument list
> argument types are: (int)
> object type is: caffe::LayerParameter
> 
> ./include/caffe/layers/conv_lstm_layer.hpp(48): warning: field initializers are a C++11 feature
> 
> 10 errors detected in the compilation of "/tmp/tmpxft_00003098_00000000-5_conv_lstm_unit_layer.cpp4.ii".
> Makefile:606: recipe for target '.build_release/cuda/src/caffe/layers/conv_lstm_unit_layer.o' failed
> make: *** [.build_release/cuda/src/caffe/layers/conv_lstm_unit_layer.o] Error 1
> make: *** Waiting for unfinished jobs....
> 
> But there is no problem in compiling the original caffe. What's the reason for this?

您是怎么解决这个问题的

**Comment by DengPingFan** [comment]
Maybe you can follow the solution&nbsp;https://github.com/DengPingFan/DAVSOD/issues/2




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"MengqiDLuffy"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月28日(星期五) 下午4:22
收件人:&nbsp;"DengPingFan/DAVSOD"<DAVSOD@noreply.github.com&gt;;
抄送:&nbsp;"Deng-Ping Fan"<381620505@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [DengPingFan/DAVSOD] make: *** [.build_release/cuda/src/caffe/layers/conv_lstm_unit_layer.o] Error 1 (#2)



 
when i build mycaffe-convlstm, The problem arises：
 
./include/caffe/layers/conv_lstm_layer.hpp(48): warning: field initializers are a C++11 feature
 
./include/caffe/layers/conv_lstm_layer.hpp(48): warning: field initializers are a C++11 feature
 
./include/caffe/layers/conv_lstm_layer.hpp(48): warning: field initializers are a C++11 feature
 
./include/caffe/layers/conv_lstm_layer.hpp(48): warning: field initializers are a C++11 feature
 
./include/caffe/layers/conv_lstm_layer.hpp(48): warning: field initializers are a C++11 feature
 
./include/caffe/layers/conv_lstm_layer.hpp(48): warning: field initializers are a C++11 feature
 
./include/caffe/layers/conv_lstm_layer.hpp(48): warning: field initializers are a C++11 feature
 
./include/caffe/layers/conv_lstm_helper.hpp(88): error: explicit type is missing ("int" assumed)
 
./include/caffe/layers/conv_lstm_helper.hpp(88): error: expected a ";"
 
./include/caffe/layers/conv_lstm_helper.hpp(88): error: expected an expression
 
./include/caffe/layers/conv_lstm_helper.hpp(88): error: expected a ";"
 
./include/caffe/layers/conv_lstm_helper.hpp(89): error: no instance of overloaded function "caffe::LayerParameter::add_bottom" matches the argument list
 argument types are: (int)
 object type is: caffe::LayerParameter
 
./include/caffe/layers/conv_lstm_helper.hpp(137): error: explicit type is missing ("int" assumed)
 
./include/caffe/layers/conv_lstm_helper.hpp(137): error: expected a ";"
 
./include/caffe/layers/conv_lstm_helper.hpp(137): error: expected an expression
 
./include/caffe/layers/conv_lstm_helper.hpp(137): error: expected a ";"
 
./include/caffe/layers/conv_lstm_helper.hpp(138): error: no instance of overloaded function "caffe::LayerParameter::add_bottom" matches the argument list
 argument types are: (int)
 object type is: caffe::LayerParameter
 
./include/caffe/layers/conv_lstm_layer.hpp(48): warning: field initializers are a C++11 feature
 
10 errors detected in the compilation of "/tmp/tmpxft_00003098_00000000-5_conv_lstm_unit_layer.cpp4.ii".
 Makefile:606: recipe for target '.build_release/cuda/src/caffe/layers/conv_lstm_unit_layer.o' failed
 make: *** [.build_release/cuda/src/caffe/layers/conv_lstm_unit_layer.o] Error 1
 make: *** Waiting for unfinished jobs....
 
But there is no problem in compiling the original caffe. What's the reason for this?
  
您是怎么解决这个问题的
