### ISSUE TITLE
matlab的测试代码两次运行一次报错一次不报错?

### ISSUE THREAD

**Issue by aflyingnoob** [DengPingFan/DAVSOD#20]
- 很神奇, 同样的环境运行, 又时会报错"Error occurs in the path"Error occurs in the path... 有时候不会报错, 但是好像不影响最终结果. 
- 此外, 有什么加速方式吗, 测试一次DAVSOD需要1.5个小时了, 好慢惹.
谢谢解答.

**Comment by DengPingFan** [comment]
1. 看下发生错误的时候是第几个sequence或者是第几张图片，下个断点看下。
2. 这里有python版本的，可以相应的更改一下：https://github.com/mczhuge/SOCToolbox

**Comment by aflyingnoob** [comment]
请问下maxF指标不是直接平均所有视频的maxF吗？我尝试计算了[DAVSOD.txt](https://github.com/DengPingFan/DAVSOD/blob/master/evalResult/SSAV/DAVSOD_result.txt)里的指标，除了maxF指标对不上，其他指标都是平均了35个视频的和.
