### ISSUE TITLE
Pre-computed saliency maps are not available.

### ISSUE THREAD

**Issue by DLUT-yyc** [DengPingFan/DAVSOD#21]
Pre-computed saliency maps and Datasets: http://dpfan.net/DAVSOD/ are not available, could you please update a valid link? Thank you very much!

**Comment by DengPingFan** [comment]
You can refer to the link: http://web.archive.org/web/20220112055406/http://dpfan.net/davsod/ 
Note that the map link can also be copied and removed the former link http://web.archive.org/web/20220112055406

Best,

**Comment by DLUT-yyc** [comment]
Extremely grateful！
