### ISSUE TITLE
训练代码

### ISSUE THREAD

**Issue by suzhipeng** [DengPingFan/DAVSOD#3]
您好，不能给训练的代码么？

**Comment by DengPingFan** [comment]
训练的代码给了呀，train.prototxt就是

**Comment by suzhipeng** [comment]
好的，谢谢🙏


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: DengPingFan <notifications@github.com>
发送时间: 2019年6月5日 16:26
收件人: DengPingFan/DAVSOD <DAVSOD@noreply.github.com>
抄送: suzhipeng <229602421@qq.com>, Author <author@noreply.github.com>
主题: 回复：[DengPingFan/DAVSOD] 训练代码 (#3)




训练的代码给了呀，train.prototxt就是
