### ISSUE TITLE
Chaging batch size for training

### ISSUE THREAD

**Issue by BrennoCaldato** [DengPingFan/DAVSOD#4]
Hi, thank you for sharing the code this is a very interesting implementation. I was trying to change the batch size for training but I can figure it out how to do so. I changed the batch size on the clip_markers layer on the train.prototxt but that causes a error of shape mismatch error:
recurrent_layer.cpp:25] Check failed: T_ == bottom[1]->shape(0) (3 vs. 2) 
I tried also changing the variable "T" on the build_hdf5.py file and compiling it again but I wasn't able to fix this, can you shed a light into how I can do this?
Thank you.

**Comment by DengPingFan** [comment]
Hi, 
    Please carefully check whether you have change all of the parts in the train.prototxt. 
for example: 

layer{
  name: "reshape-data"
  type: "Reshape"
  bottom: "conv5_4"
  top: "conv5_4-reshape"
  reshape_param{
    shape{
      dim: 3 #T
      dim: 1 #N
      dim: 32 #C
      dim: 60 #H
      dim: 60 #W
    }
  }
}

**Comment by BrennoCaldato** [comment]
hi, thanks for the explanation. I changed all the parts in the train.prototxt but I'm still having a shape mismatch in the reshape-data layer:

I0704 20:19:06.857492 17499 layer_factory.hpp:77] Creating layer reshape-data
I0704 20:19:06.857499 17499 net.cpp:84] Creating Layer reshape-data
I0704 20:19:06.857504 17499 net.cpp:406] reshape-data <- conv5_4
I0704 20:19:06.857512 17499 net.cpp:380] reshape-data -> conv5_4-reshape
F0704 20:19:06.857566 17499 reshape_layer.cpp:87] Check failed: top[0]->count() == bottom[0]->count() (230400 vs. 345600) output count must match input count
*** Check failure stack trace: ***
Aborted (core dumped)

Did I miss something in other parts of the code?

**Comment by DengPingFan** [comment]
Not that you still need to grantee the same size of the input and output channel. 
 reshape-data <- conv5_4
I0704 20:19:06.857512 17499 net.cpp:380] reshape-data -> conv5_4-reshape.
You much check each of them carefully. I recommend you use the online Netscope CNN Analyzer tool: https://dgschwend.github.io/netscope/quickstart.html
