### ISSUE TITLE
File "/DAVSOD/sequence_input_layer.py", line 278 new_result_data = [None]*len(self.thread_result['data'])  KeyError: 'data'

### ISSUE THREAD

**Issue by jjkislele** [DengPingFan/DAVSOD#5]
Hi, thank you for sharing code. It's a sota work in vsod.

While during the training phase, some bugs arised:

```
Traceback (most recent call last):
  File "run_SSAVsaliency.py", line 62, in <module>
    solver.step(50000)
  File "/DAVSOD/sequence_input_layer.py", line 278, in forward
    new_result_data = [None]*len(self.thread_result['data']) 
KeyError: 'data'
```

I guess maybe in ``train.prototxt`` some layers missed. Although I'm a totally novice for using caffe. So please give me some hits.

Besides, code works in ``py35, cuda10.1, cudnn 7.6.0``. Easy to test, but bugs arised during training.

Looking forwards for your reply, thx.

**Comment by DengPingFan** [comment]
hi, I think you have two choices:
first, you set your work environment as unbutu 16.04 with CUDA 8.0 and OpenCV 3.1.0.
second, maybe you have changed the parameter in the file of sequence_input_layer.py. Please note that you should regenerate the file of seq_t5_n1.txt.

This is the first time you encounter this error. Other guys doesn't have this issues.

**Comment by jjkislele** [comment]
Well, thank you for your reply. After heavily debugging,  I think I find where is going wrong. In ``sequence_input_layer.py`` lines 104-106
```
im_info = zip(im_paths, im_reshape)
label_info = zip(label_paths, im_reshape)
att_info = zip(att_paths,im_reshape)
```
we need to modify these lines to:
```
im_info = list(zip(im_paths, im_reshape))
label_info = list(zip(label_paths, im_reshape))
att_info = list(zip(att_paths,im_reshape))
```
because of the version problem caused by py36.

-> [stackoverflow](https://stackoverflow.com/questions/31011631/python-2-3-object-of-type-zip-has-no-len)
> Unfortunately, operator.length_hint() (Python 3.4+) returns zero for a zip() object.
