### ISSUE TITLE
This code can run with CUDA10?

### ISSUE THREAD

**Issue by alongGS** [DengPingFan/DAVSOD#7]

**Comment by DengPingFan** [comment]
Hi, The default setting is CUDA 8.0, if you want to run in CUDA 10,  maybe you need re-confige it.

**Comment by alongGS** [comment]
> Hi, The default setting is CUDA 8.0, if you want to run in CUDA 10, maybe you need re-confige it.

ok , thinks, but I think that will create other problems in future. these are pytorch or tensorflow code?

**Comment by alongGS** [comment]
> Hi, The default setting is CUDA 8.0, if you want to run in CUDA 10, maybe you need re-confige it.

ok , thanks, but I think that will create other problems in future. these are pytorch or tensorflow code?

**Comment by DengPingFan** [comment]
Due to commercial use, we may not share the PyTorch code.

**Comment by DengPingFan** [comment]
Due to commercial use, we may not share the PyTorch code.
