### ISSUE TITLE
Do you interpolate the saliency map from 60x60 into 473x473 during training?

### ISSUE THREAD

**Issue by learnerRen** [DengPingFan/DAVSOD#8]
If so, why the saliency map so smooth. I downsample the GT to 60x60 and re-interpolate to the original size, but the new saliency map is far from your saliency map.
![new_new](https://user-images.githubusercontent.com/34859446/66625732-1663d880-ec28-11e9-8144-2add5a39aa3e.png)

**Comment by DengPingFan** [comment]
Yes, you need to resize 60*60 predicted map to the 473*473 resolution during training stage.

**Comment by learnerRen** [comment]
> Yes, you need to resize 60_60 predicted map to the 473_473 resolution during training stage.

I see the code 60x60x1 interpolate to 473x473x1 and add a sigmoid during training. Can bilinear interpolation interpolate a 60x60 to 473x473 image with such good quality?  I use GT downsample and re-interpolate and the boundary is clearly serrated.  I don't know if I make a mistake in the training process. Thanks~

**Comment by DengPingFan** [comment]
You can train with this our SSAV model then visualize the results so that you can easy to analyze the results. I don't whether the bilinear interpolation could achieve wihtout serrated. Maybe you can change another interpolation method.

best,
