### ISSUE TITLE
测试图片序列问题请教

### ISSUE THREAD

**Issue by byh1990** [DengPingFan/DAVSOD#9]
1.我用自己的图片序列，测试咱们的demo，发现跑出来的结果不正常，人不是人，车不是车，分割的目标不清楚
2.只能识别出大点的目标，像素大约在100*100以上的，对于50*50以下的目标，基本识别不出来
3.我看咱们提供的样例，基本上是大目标，目标少，场景简单的情况，而我们自己的时场景复杂，目标众多，且目标大小不一，从几十到上百个像素的都有。
4.以上这些情况是否需要对我们自己的视频序列进行分割级别的标注，然后训练一下网络，重新跑自己的图片序列？
因为我们的场景特别复杂，使用车载相机拍摄的大广角画面。对于这样的场景，您这边推荐不推荐使用你们提供算法进行图像的标注？感觉标注出来也不准确，还需要大量的人力进行review，尤其是小目标，基本上识别不出来

**Comment by DengPingFan** [comment]
对于这种特别复杂的场景，你需要把模型进行finetune或者重新训练一下，因为并行的空洞卷积和已经见过的图片有了一部分拟合了。并且对于这样50*50的小物体本来对物体检测来说也就是一个open problem. 
建议做法：
1.人工标注几类典型的图片
2.分别进行数据增强，并且重新finetune一下。
3.如果数据能标注的更多，那么就重新训练效果会更好。

**Comment by byh1990** [comment]
感谢您的回复，从我对您论文原理得知，需要满足“显著性”这三个字，不显著的可能就废了，不过对于我们的简单场景，提供了很好地自动化标注策略，节省了人力成本，还有就是，老师您这边提供的网络性能还能继续提升么？

**Comment by DengPingFan** [comment]
1.这个网络也可以解决不是那么显著的，你给什么数据，他就能学习什么数据，可以理解为类别无关的物体分割模型吧，很多显著性网络也都会从物体检测领域借鉴一些方法或者模块过来。

2.AAAI2020有一篇文章采用了另外一个思路，网络性能进一步提高了，还有另外一篇最近审稿到的论文也对这个网络改进了，也有提高。你可以考虑吧前面静态网络换成最近更好的模型。后面的LSTM可以考虑用一些non-local的方法（何凯明的论文）进行改进。
